// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/notrehab/NotrehabCoffeeDaybreakIndex.tsx": () => import("../components/mockups/notrehab/NotrehabCoffeeDaybreakIndex.tsx"),
  "./components/mockups/notrehab/NotrehabCoffeeFieldManual.tsx": () => import("../components/mockups/notrehab/NotrehabCoffeeFieldManual.tsx"),
  "./components/mockups/notrehab/NotrehabCoffeeRitualConsole.tsx": () => import("../components/mockups/notrehab/NotrehabCoffeeRitualConsole.tsx"),
  "./components/mockups/templates/RustArchitectureSignup-0SykqJ/App.tsx": () => import("../components/mockups/templates/RustArchitectureSignup-0SykqJ/App.tsx")
};
